name: run_line_weather_focus

on:
  push:
    branches: [main]
  schedule:
    # github actions のデフォルトの time zone が UTC なので、日本時間 - 9時間 した値を書く
    - cron:  '2 5 * * *'
  #pull_request:
  workflow_dispatch:
    branches: [main]

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Get Python version
        run: python -V
      - name: Run Python
        run: 
            python post_line_message.py
        env:
            prefecture_code: ${{secrets.PREFECTURE_CODE}}
            local_code: ${{secrets.LOCAL_CODE}}
            municipality_code: ${{secrets.MUNICIPALITY_CODE}}
            LINE_TOKEN: ${{secrets.LINE_TOKEN}}

